version: '3.9'

services:
  redis_syntax:
    container_name: ${REDIS_HOST}
    hostname: ${REDIS_HOST}
    image: redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf
